### ISSUE TITLE
can you add wiki

### ISSUE THREAD

**Issue by malikshi** [Datamart/CGI-Proxy#1]
please add wiki or usage for newbie there,

**Comment by vpodk** [comment]
@malikshi, thanks for the request. We will definitely do it soon.

**Comment by malikshi** [comment]
@vpodk Thanks A lot Sir

**Comment by vpodk** [comment]
Hi @malikshi, we updated the [README](https://github.com/Datamart/CGI-Proxy/blob/master/README.md) file with method descriptions and examples. Please let us know if you have any questions.
